stages: # Lista de etapas
  - build
  - test
 
build: # Nombre del trabajo
  image: gradle:7.6.1-jdk8
  stage: build # Etapa a la cual pertenece
  script: # Ejecutar scripts, comandos, etc
    - sh $CI_PROJECT_DIR/gradlew assemble

acceptance-test: # Nombre del trabajo
  image: rvancea/gradle-chrome-jdk8:latest
  stage: test # Etapa a la cual pertenece
  script: # Ejecutar scripts, comandos, etc
    - sh $CI_PROJECT_DIR/gradlew test -i
  artifacts:
    paths:
      - build/karate-reports
      - build/reports